# app/config/common/config_vich.yml
twig:
    form_themes:
        - 'VichUploaderBundle:Form:fields.html.twig'

vich_uploader:
    db_driver: orm

    mappings:
        book_cover:
            uri_prefix:         /uploads/books/covers
            upload_destination: %kernel.root_dir%/../www/uploads/books/covers
            namer:              vich_uploader.namer_uniqid
            delete_on_remove:   true
            delete_on_update:   true